create extension if not exists pgcrypto;

create table if not exists players (
    id uuid primary key default gen_random_uuid(),
    name text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists picks (
    id bigint generated by default as identity primary key,
    player_id uuid not null references players(id) on delete cascade,
    week integer not null check (week between 1 and 22),
    team text not null,
    opponent text,
    result text not null default 'pending'
        check (result in ('pending','win','loss')),
    settled_at timestamptz,
    created_at timestamptz not null default now(),
    unique(player_id, week)
);

create table if not exists settings (
    key text primary key,
    value text not null
);

insert into settings(key, value)
values
    ('current_week', '1'),
    ('admin_name', '')
on conflict (key) do nothing;

create index if not exists picks_player_idx on picks(player_id);
create index if not exists picks_week_idx on picks(week);

-- This app intentionally uses a single Supabase server-side credential and
-- name-based player selection for a small private league.
-- If you later make it public, add Supabase Auth + RLS.
